<a href="https://colab.research.google.com/github/kboyles8/CAP4630/blob/master/HW_4/HW4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Problem 1

In this problem, the `conv2d` function is implemented from scratch using numpy. This function takes in the input and kernel array and outputs the convolution array.

The process starts in the top left corner of the input array. The kernel is multiplied into a section of the input array equal to its size, and the resulting matrix is summed and placed into position (0, 0) in the output array. The kernel is then shifted right by one, and the process continues until the end of the input array is reached. The kernel moves to the next row and continues.

## Initial Setup

In [0]:
import numpy as np

## Define the Function

In [0]:
"""
Calculates the 2D convolution of input_mat using kernel_mat as a filter.
input_mat and kernel_mat are assumed to be square matrices.
The kernel cannot be larger than the input.
"""
def conv2d(input_mat: np.array, kernel_mat: np.array) -> np.array:
    input_size = input_mat.shape[0]
    kernel_size = kernel_mat.shape[0]

    if kernel_size > input_size:
        raise ValueError("The kernel cannot be larger than the input")

    # Calculate the size of the output array
    output_size = input_size - kernel_size + 1

    # Create output array
    output_mat = np.zeros((output_size, output_size))

    # Colvolve
    for y_pos in range(output_size):
        for x_pos in range(output_size):
            # Apply kernel and sum
            output_mat[y_pos][x_pos] = np.sum(input_mat[y_pos:y_pos+kernel_size, x_pos:x_pos+kernel_size] * kernel_mat)

    return output_mat

## Test the Function

In [3]:
input_mat = np.array([[1, 2, 1, 2],
                      [2, 1, 2, 1],
                      [1, 2, 1, 2],
                      [2, 1, 2, 1]])

kernel_mat = np.array([[1, 0],
                       [0, 1]])

expected_output_mat = np.array([[2, 4, 2],
                                [4, 2, 4],
                                [2, 4, 2]])

output_mat = conv2d(input_mat, kernel_mat)

print(output_mat)

if np.array_equal(output_mat, expected_output_mat):
    print("Correct output!")
else:
    print("Incorrect output!")


[[2. 4. 2.]
 [4. 2. 4.]
 [2. 4. 2.]]
Correct output!


# Problem 2

In this problem, the maxpooling2d function is implemented from scratch using numpy. This function takes in the input and a window size and outputs the maxpooled array. The stride is assumed to be the size of the window. This uses the default behavior of Keras, which does not pad the input.

The process starts in the top left corner of the input array. The maximum value within an s by s region is found and placed into the output array at (0, 0). The window moves right by s, and the process repeats until the window cannot fit into the input array. The window then moves down s and back to the left of the input array. This continues until the window falls off the bottom of the input array.

## Define the Function

In [0]:
"""
Calculates the MaxPool of input_mat using a window of size s.
input_mat is assumed to be a square matrix.
The stride is assumed to be the size of the window.
The input is not padded if the window cannot fit all of the remaining input matrix, as per the default behavior of Keras.
"""
def maxpooling2d(input_mat: np.array, window_size: int) -> np.array:
    input_size = input_mat.shape[0]

    if window_size > input_size:
        raise ValueError("The window size cannot be larger than the input")

    # Calculate the size of the output array
    output_size = input_size // window_size

    # Create output array
    output_mat = np.zeros((output_size, output_size))

    # Perform MaxPooling
    for y_stride in range(output_size):
        y_pos = y_stride * window_size
        for x_stride in range(output_size):
            x_pos = x_stride * window_size

            # Find the max
            output_mat[y_stride][x_stride] = np.amax(input_mat[y_pos:y_pos+window_size, x_pos:x_pos+window_size])

    return output_mat

## Test the Function

In [5]:
input_mat = np.array([[1, 2, 1, 2],
                      [2, 4, 2, 1],
                      [1, 2, 4, 2],
                      [2, 1, 2, 1]])

expected_output_mat = np.array([[4, 2],
                                [2, 4]])

output_mat = maxpooling2d(input_mat, 2)

print(output_mat)

if np.array_equal(output_mat, expected_output_mat):
    print("Correct output!")
else:
    print("Incorrect output!")

[[4. 2.]
 [2. 4.]]
Correct output!
