<a href="https://colab.research.google.com/github/kboyles8/CAP4630/blob/master/HW_4/HW4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Problem 1

In this problem, the `conv2d` function is implemented from scratch using numpy. This function takes in the input and kernel array and outputs the convolution array.

The process starts in the top left corner of the input array. The kernel is multiplied into a section of the input array equal to its size, and the resulting matrix is summed and placed into position (0, 0) in the output array. The kernel is then shifted right by one, and the process continues until the end of the input array is reached. The kernel moves to the next row and continues.

## Initial Setup

In [0]:
import numpy as np

## Define the Function

In [0]:
"""
Calculates the 2D convolution of input_mat using kernel_mat as a filter.
input_mat and kernel_mat must be square matrices.
The kernel cannot be larger than the input.
"""
def conv2d(input_mat: np.array, kernel_mat: np.array) -> np.array:
    if (input_mat.shape[0] != input_mat.shape[1]):
        raise ValueError("The input matrix must be square")
    if (kernel_mat.shape[0] != kernel_mat.shape[1]):
        raise ValueError("The kernel matrix must be square")

    input_size = input_mat.shape[0]
    kernel_size = kernel_mat.shape[0]

    if kernel_size > input_size:
        raise ValueError("The kernel cannot be larger than the input")

    # Calculate the size of the output array
    output_size = input_size - kernel_size + 1

    # Create output array
    output_mat = np.zeros((output_size, output_size))

    # Colvolve
    for y_pos in range(output_size):
        for x_pos in range(output_size):
            # Apply kernel and sum
            output_mat[y_pos][x_pos] = np.sum(input_mat[y_pos:y_pos+kernel_size, x_pos:x_pos+kernel_size] * kernel_mat)

    return output_mat

## Test the Function

In [25]:
import numpy as np

input_mat = []
kernel_mat = []
expected_mat = []

# test case 1
input_mat.append(np.array([[1, 2, 1, 2],
                           [2, 1, 2, 1],
                           [1, 2, 1, 2],
                           [2, 1, 2, 1]]))

kernel_mat.append(np.array([[1, 0],
                            [0, 1]]))

expected_mat.append(np.array([[2, 4, 2],
                              [4, 2, 4],
                              [2, 4, 2]]))

# test case 2
input_mat.append(np.array([[1, 0, 0, 0],
                           [0, 1, 0, 0],
                           [0, 0, 1, 0],
                           [0, 0, 0, 1]]))
kernel_mat.append(np.array([[1, 0], [0, 1]]))
expected_mat.append(np.array([[2, 0, 0], [0, 2, 0], [0, 0, 2]]))


# test case 3
input_mat.append(np.array([[1, 0, 0, 0],
                           [0, 1, 0, 0],
                           [0, 0, 1, 0],
                           [0, 0, 0, 1]]))

kernel_mat.append(np.array([[1, -1],
                            [-1, 0]]))

expected_mat.append(np.array([[ 1, -1,  0], [-1,  1, -1],[ 0, -1,  1]]))


# test case 4
input_mat.append(np.array([[1, 0, 0, 0],
                           [0, 1, 0, 0],
                           [0, 0, 1, 0],
                           [0, 0, 0, 1]]))

kernel_mat.append(np.array([[1, 0, 0, 0],
                            [0, 1, 0, 0],
                            [0, 0, 1, 0],
                            [0, 0, 0, 1]]))

expected_mat.append(np.array([[4]]))


# test case 5 - should throw an error due to the kernel being larger than the input
input_mat.append(np.array([[1, -1],
                           [-1, 0]]))

kernel_mat.append(np.array([[1, 0, 0, 0],
                            [0, 1, 0, 0],
                            [0, 0, 1, 0],
                            [0, 0, 0, 1]]))

expected_mat.append(None)


# test case 6 - should throw an exception due to the input not being square
input_mat.append(np.array([[1, -1, 1],
                           [-1, 0, -1]]))

kernel_mat.append(np.array([[1, 0],
                            [0, 1]]))

expected_mat.append(None)


# test case 7 - should throw an exception due to the kernel not being square
input_mat.append(np.array([[1, -1],
                           [-1, 0]]))

kernel_mat.append(np.array([[1, 0]]))

expected_mat.append(None)



for i in range(len(input_mat)):
    try:
        output_mat = conv2d(input_mat[i], kernel_mat[i])

        print(output_mat)
        if np.array_equal(output_mat, expected_mat[i]):
            print("Correct output!")
        else:
            print("Incorrect output!")
    except Exception as e:
        print(e)

        if expected_mat[i] == None:
            print("Correct output!")
        else:
            print("Incorrect output!")
    
    print()

[[2. 4. 2.]
 [4. 2. 4.]
 [2. 4. 2.]]
Correct output!

[[2. 0. 0.]
 [0. 2. 0.]
 [0. 0. 2.]]
Correct output!

[[ 1. -1.  0.]
 [-1.  1. -1.]
 [ 0. -1.  1.]]
Correct output!

[[4.]]
Correct output!

The kernel cannot be larger than the input
Correct output!

The input matrix must be square
Correct output!

The kernel matrix must be square
Correct output!



# Problem 2

In this problem, the maxpooling2d function is implemented from scratch using numpy. This function takes in the input and a window size and outputs the maxpooled array. The stride is assumed to be the size of the window. This uses the default behavior of Keras, which does not pad the input.

The process starts in the top left corner of the input array. The maximum value within an s by s region is found and placed into the output array at (0, 0). The window moves right by s, and the process repeats until the window cannot fit into the input array. The window then moves down s and back to the left of the input array. This continues until the window falls off the bottom of the input array.

## Define the Function

In [0]:
"""
Calculates the MaxPool of input_mat using a window of size s.
input_mat must be a square matrix.
The stride is assumed to be the size of the window.
The input is not padded if the window cannot fit all of the remaining input matrix, as per the default behavior of Keras. This is not a requirement of the problem.
"""
def maxpooling2d(input_mat: np.array, window_size: int) -> np.array:
    if (input_mat.shape[0] != input_mat.shape[1]):
        raise ValueError("The input matrix must be square")

    input_size = input_mat.shape[0]

    if window_size > input_size:
        raise ValueError("The window size cannot be larger than the input")

    # Calculate the size of the output array
    output_size = input_size // window_size

    # Create output array
    output_mat = np.zeros((output_size, output_size))

    # Perform MaxPooling
    for y_stride in range(output_size):
        y_pos = y_stride * window_size
        for x_stride in range(output_size):
            x_pos = x_stride * window_size

            # Find the max
            output_mat[y_stride][x_stride] = np.amax(input_mat[y_pos:y_pos+window_size, x_pos:x_pos+window_size])

    return output_mat

## Test the Function

In [27]:
input_mat = []
expected_mat = []
s = []

# test case 1
input_mat.append(np.array([[1, 2, 1, 2],
                           [2, 4, 2, 1],
                           [1, 2, 4, 2],
                           [2, 1, 2, 1]]))
s.append(2)

expected_mat.append(np.array([[4, 2],
                              [2, 4]]))


# test case 2 - should throw an exception due to the input not being square
input_mat.append(np.array([[1, 2, 1, 2, 4, 5],
                           [2, 4, 2, 1, 0, 3],
                           [1, 2, 4, 2, 4, 5],
                           [2, 1, 2, 1, 2, 1],
                           [1, 1, 2, 3, 1, 2]]))
s.append(2)

expected_mat.append(None)


# test case 3 - should throw an exception due to the window being larger than the input
input_mat.append(np.array([[1, -1],
                           [-1, 0]]))

s.append(3)

expected_mat.append(None)


for i in range(len(input_mat)):
    try:
        output_mat = maxpooling2d(input_mat[i], s[i])

        print(output_mat)

        if np.array_equal(output_mat, expected_mat[i]):
            print("Correct output!")
        else:
            print("Incorrect output!")
    except Exception as e:
        print(e)

        if expected_mat[i] == None:
            print("Correct output!")
        else:
            print("Incorrect output!")
    
    print()


[[4. 2.]
 [2. 4.]]
Correct output!

The input matrix must be square
Correct output!

The window size cannot be larger than the input
Correct output!

