<a href="https://colab.research.google.com/github/kboyles8/CAP4630/blob/master/HW_1/HW_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Project Description

The goal of this project is to create a function that, given a list of matrices, calculates the product of all matrices in left to right order, or throws an exception if this is not possible. Order is important, as there are rules about how matrices can be multiplied.

## Matrix multiplication rules

Two matrices can be multiplied only if the number of columns of the first matrix is equal to the number of rows of the second matrix. For example, the following matrices are compatible, as the first matrix has 2 columns, and the second matrix has 2 rows.

$\begin{bmatrix}
1 & 2 \\
3 & 4 \\
5 & 6
\end{bmatrix}
\begin{bmatrix}
1 & 2 & 1 \\
2 & 1 & 2
\end{bmatrix}
=
\begin{bmatrix}
5 & 4 & 5 \\
11 & 10 & 11 \\
17 & 16 & 17
\end{bmatrix}$

However, the following matrices are not compatible, as the first matrix has **2** columns and the second matrix has **3** rows. These matrices can not be multiplied.

$\begin{bmatrix}
1 & 2 \\
3 & 4 \\
5 & 6
\end{bmatrix}
\begin{bmatrix}
1 & 2 \\
2 & 1 \\
1 & 2 \\
\end{bmatrix}
=
ERROR$

# The matrix multiplication function

Below is the code for the matrix multiplication function. It takes a list of matrices and calculates the product, throwing an exception if any of the matrices are not compatible.

In [0]:
from typing import List
import numpy as np


def multiply_matrices(matrices: List[np.array]) -> np.array:
    # Handle the empty case
    if (len(matrices) == 0):
        return []

    # Check if the matricies can be multiplied together
    for i in range(len(matrices)-1):
        # If number of columns of the first matrix does not match the number of
        # rows of the second matrix
        if (matrices[i].shape[1] != matrices[i+1].shape[0]):
            raise ValueError(
                f'Matrix {i} {matrices[i].shape} is not compatible with '
                f'matrix {i+1} {matrices[i+1].shape}'
            )

    # Perform multiplication
    result_matrix = matrices[0]
    for matrix in matrices[1:]:
        result_matrix = np.matmul(result_matrix, matrix)

    return result_matrix


# Testing the matrix multiplication function

In this section, several tests are performed on the matrix multiplication function to ensure it functions correctly.

## Testing a valid matrix multiplication

This tests two matrices that are compatible

In [26]:
test_matricies_good = [
    np.array([[1, 2],
              [3, 4],
              [5, 6]]),

    np.array([[1, 2, 1],
              [2, 1, 2]])
]

print(multiply_matrices(test_matricies_good))


[[ 5  4  5]
 [11 10 11]
 [17 16 17]]


## Testing an invalid matrix multiplication

This tests two matrices that are **not** compatible

In [27]:
test_matricies_invalid = [
    np.array([[1, 2],
              [3, 4],
              [5, 6]]),

    np.array([[1, 2],
              [2, 1],
              [1, 2]])
]

try:
    print(multiply_matrices(test_matricies_invalid))
except ValueError as ex:
    print(ex)


Matrix 0 (3, 2) is not compatible with matrix 1 (3, 2)


## Testing the trivial cases

This tests two trivial cases: where only a single matrix is provided, and when no matrices are provided. It was decied to handle these by returning the given matrix and an empty matrix, respectively.

### A single matrix

In [28]:
test_matricies_trivial = [
    np.array([[1, 2],
              [3, 4],
              [5, 6]])
]

print(multiply_matrices(test_matricies_trivial))


[[1 2]
 [3 4]
 [5 6]]


### No matrices

In [29]:
test_matricies_trivial_empty = []

print(multiply_matrices(test_matricies_trivial_empty))


[]
